# Generated by Django 4.0.4 on 2022-09-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0012_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_subtitle',
            field=models.TextField(default='Hello', max_length=100),
            preserve_default=False,
        ),
    ]
